"""empty message

Revision ID: 83758d1fa6a0
Revises: ebef230ef7c8
Create Date: 2022-03-02 11:52:16.316547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83758d1fa6a0'
down_revision = 'ebef230ef7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
